defaults:
  - _default_optimization_attack
  - _self_
type: invertinggradients

objective:
  type: cosine-similarity
  scale: 1.0 # need to have a much smaller scale like 0.0001 for euclidean objectives

init: patterned-4

restarts:
  num_trials: 4
  scoring: "cosine-similarity"

optim:
  optimizer: adam
  signed: "soft"
  step_size: 0.1
  boxed: True
  # max_iterations: 24_000
  max_iterations: 5000
  step_size_decay: cosine-decay
  warmup: 50

  patched:
  # callback: 1000 # Print objective value every callback many iterations
  callback: 100 # Print objective value every callback many iterations

regularization:
  total_variation:
    scale: 0.1
    inner_exp: 2
    outer_exp: 0.5
    double_opponents: True
  features:
    scale: 0.1
  deep_inversion:
    scale: 0.0001

accelerate:
  add_noise:
    # interval: 1000
    # scale: 0.01
    # num_levels: 20

out_dir: "/home/zx/Gitrepo/breaching/out/patch_benchmark/modern/origin"
layer_weights: "equal"